"""initial database schema with simulation

Revision ID: 89db6f2f8dd9
Revises: 
Create Date: 2026-08-23 21:10:25.029094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89db6f2f8dd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('external_product_code', sa.String(length=100), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('product_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('join_target', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('external_product_code')
    )
    op.create_table('market_assets',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('asset_type', sa.String(length=10), nullable=False),
    sa.Column('market', sa.String(length=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('asset_id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('representative_badge_id', sa.Integer(), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('login_locked_until', sa.DateTime(), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('accounts',
    sa.Column('account_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=12), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('account_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('financial_product_options',
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('base_interest_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('max_interest_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('interest_method', sa.String(length=30), nullable=False),
    sa.Column('min_amount', sa.BigInteger(), nullable=False),
    sa.Column('max_amount', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['financial_products.product_id'], ),
    sa.PrimaryKeyConstraint('option_id'),
    sa.UniqueConstraint('product_id', 'term_months', 'interest_method', name='uq_product_option_term_method')
    )
    op.create_table('market_holdings',
    sa.Column('holding_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('total_acquisition_cost', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('total_acquisition_cost_krw', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['market_assets.asset_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('holding_id'),
    sa.UniqueConstraint('user_id', 'asset_id', name='uq_market_holdings_user_asset')
    )
    op.create_table('market_transactions',
    sa.Column('market_transaction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('amount_krw', sa.BigInteger(), nullable=False),
    sa.Column('market_session', sa.String(length=10), nullable=False),
    sa.Column('fee', sa.BigInteger(), nullable=False),
    sa.Column('tax', sa.BigInteger(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['market_assets.asset_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('market_transaction_id')
    )
    op.create_table('monthly_cash_flows',
    sa.Column('monthly_cash_flow_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('income_amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('income_amount >= 0', name='ck_monthly_cash_flows_income_amount'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('monthly_cash_flow_id'),
    sa.UniqueConstraint('user_id', 'year_month', name='uq_monthly_cash_flows_user_year_month')
    )
    op.create_table('simulation_settings',
    sa.Column('simulation_setting_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('initial_asset', sa.BigInteger(), nullable=False),
    sa.Column('is_initial_asset_set', sa.Boolean(), nullable=False),
    sa.Column('monthly_income', sa.BigInteger(), nullable=False),
    sa.Column('monthly_expense', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('initial_asset >= 0 AND initial_asset <= 100000000', name='ck_simulation_initial_asset'),
    sa.CheckConstraint('monthly_expense <= monthly_income', name='ck_simulation_expense_income'),
    sa.CheckConstraint('monthly_expense >= 0 AND monthly_expense <= 10000000', name='ck_simulation_monthly_expense'),
    sa.CheckConstraint('monthly_income >= 0 AND monthly_income <= 10000000', name='ck_simulation_monthly_income'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('simulation_setting_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('social_accounts',
    sa.Column('social_account_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('social_account_id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_social_provider_user')
    )
    op.create_table('deposits',
    sa.Column('deposit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('principal', sa.BigInteger(), nullable=False),
    sa.Column('applied_interest_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('interest_method', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gross_interest', sa.BigInteger(), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('tax_amount', sa.BigInteger(), nullable=True),
    sa.Column('net_interest', sa.BigInteger(), nullable=True),
    sa.Column('payout_amount', sa.BigInteger(), nullable=True),
    sa.Column('applied_early_termination_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('matured_at', sa.DateTime(), nullable=True),
    sa.Column('terminated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['financial_product_options.option_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['financial_products.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('deposit_id')
    )
    with op.batch_alter_table('deposits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deposits_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_deposits_user_id'), ['user_id'], unique=False)

    op.create_table('early_termination_rate_rules',
    sa.Column('early_termination_rule_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('minimum_holding_days', sa.Integer(), nullable=False),
    sa.Column('maximum_holding_days', sa.Integer(), nullable=True),
    sa.Column('calculation_type', sa.String(length=30), nullable=False),
    sa.Column('rate_value', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('is_assumed', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['financial_product_options.option_id'], ),
    sa.PrimaryKeyConstraint('early_termination_rule_id')
    )
    op.create_table('ledger_transactions',
    sa.Column('ledger_transaction_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('balance_after', sa.BigInteger(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('ledger_transaction_id')
    )
    op.create_table('product_preference_conditions',
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('condition_code', sa.String(length=50), nullable=False),
    sa.Column('condition_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('additional_interest_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['financial_product_options.option_id'], ),
    sa.PrimaryKeyConstraint('condition_id'),
    sa.UniqueConstraint('option_id', 'condition_code', name='uq_option_condition_code')
    )
    op.create_table('savings',
    sa.Column('saving_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('monthly_amount', sa.BigInteger(), nullable=False),
    sa.Column('scheduled_payment_count', sa.Integer(), nullable=False),
    sa.Column('applied_interest_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('interest_method', sa.String(length=30), nullable=False),
    sa.Column('payment_day', sa.Integer(), nullable=False),
    sa.Column('next_payment_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_paid_principal', sa.BigInteger(), nullable=False),
    sa.Column('gross_interest', sa.BigInteger(), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('tax_amount', sa.BigInteger(), nullable=True),
    sa.Column('net_interest', sa.BigInteger(), nullable=True),
    sa.Column('payout_amount', sa.BigInteger(), nullable=True),
    sa.Column('applied_early_termination_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('matured_at', sa.DateTime(), nullable=True),
    sa.Column('terminated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['financial_product_options.option_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['financial_products.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('saving_id')
    )
    with op.batch_alter_table('savings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_savings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_savings_user_id'), ['user_id'], unique=False)

    op.create_table('deposit_preference_conditions',
    sa.Column('deposit_preference_condition_id', sa.Integer(), nullable=False),
    sa.Column('deposit_id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('condition_name', sa.String(length=100), nullable=False),
    sa.Column('additional_interest_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['product_preference_conditions.condition_id'], ),
    sa.ForeignKeyConstraint(['deposit_id'], ['deposits.deposit_id'], ),
    sa.PrimaryKeyConstraint('deposit_preference_condition_id')
    )
    op.create_table('ledger_entries',
    sa.Column('ledger_entry_id', sa.Integer(), nullable=False),
    sa.Column('ledger_transaction_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ledger_transaction_id'], ['ledger_transactions.ledger_transaction_id'], ),
    sa.PrimaryKeyConstraint('ledger_entry_id')
    )
    op.create_table('saving_payments',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('saving_id', sa.Integer(), nullable=False),
    sa.Column('payment_sequence', sa.Integer(), nullable=False),
    sa.Column('payment_year_month', sa.String(length=7), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['saving_id'], ['savings.saving_id'], ),
    sa.PrimaryKeyConstraint('payment_id'),
    sa.UniqueConstraint('saving_id', 'payment_sequence', name='uq_saving_payment_sequence')
    )
    op.create_table('saving_preference_conditions',
    sa.Column('saving_preference_condition_id', sa.Integer(), nullable=False),
    sa.Column('saving_id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('condition_name', sa.String(length=100), nullable=False),
    sa.Column('additional_interest_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['product_preference_conditions.condition_id'], ),
    sa.ForeignKeyConstraint(['saving_id'], ['savings.saving_id'], ),
    sa.PrimaryKeyConstraint('saving_preference_condition_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saving_preference_conditions')
    op.drop_table('saving_payments')
    op.drop_table('ledger_entries')
    op.drop_table('deposit_preference_conditions')
    with op.batch_alter_table('savings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_savings_user_id'))
        batch_op.drop_index(batch_op.f('ix_savings_status'))

    op.drop_table('savings')
    op.drop_table('product_preference_conditions')
    op.drop_table('ledger_transactions')
    op.drop_table('early_termination_rate_rules')
    with op.batch_alter_table('deposits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deposits_user_id'))
        batch_op.drop_index(batch_op.f('ix_deposits_status'))

    op.drop_table('deposits')
    op.drop_table('social_accounts')
    op.drop_table('simulation_settings')
    op.drop_table('monthly_cash_flows')
    op.drop_table('market_transactions')
    op.drop_table('market_holdings')
    op.drop_table('financial_product_options')
    op.drop_table('accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('market_assets')
    op.drop_table('financial_products')
    # ### end Alembic commands ###
